[package]
name = "odborna-prace-template"
version = "0.6.0"
entrypoint = "src/lib.typ"
authors = ["Patrik Marius"]
description = "Internal GJKT thesis template and review/rendering package used by DarkFactory-Paper"
