/**
 * Drafting an implementation plan and posting it for approval.
 *
 * Replaces `handle_plan` in `.github/scripts/agent_runner.py`. The plan is posted on the *plan*
 * issue, which is the parent Request itself once the two approval gates were merged onto one issue
 * and a child Plan issue for a legacy one - so both numbers are carried, and only the one the plan
 * lands on is read back.
 */

import { PLAN_FOOTER } from "../approvals/commands.ts";
import { type PipelineContext, PLAN_TIMEOUT } from "./handler-context.ts";
import { bestEffort } from "./pipeline-io.ts";
import { isPlanComment, PLAN_MARKER } from "./plan-scope.ts";
import { AGENT_ERROR_PREFIX, isQuotaExhaustionNotice, rewriteFileLinks } from "./signals.ts";

/** Marks every comment this pipeline posts, so a later pass can recognise its own output. */
const AGENT_MARKER = "<!-- darkfactory-agent -->";

/** What planning did. */
export type PlanOutcome =
	/** A plan was posted on the plan issue. */
	| { kind: "posted"; comment: string }
	/**
	 * The agent ran out of quota, so nothing was posted.
	 *
	 * The plan is the longest prompt before implementation, so this is where a run most often stops;
	 * the caller checkpoints and blocks rather than failing.
	 */
	| { kind: "quota-exhausted"; notice: string }
	/** The agent failed, an execution-error comment was posted, and the run ends non-zero. */
	| { kind: "failed"; notice: string; comment: string };

/** What to plan. */
export interface PlanRequest {
	/** The parent Request issue number. */
	requestNumber: number;
	/**
	 * The issue the plan is posted on: the parent Request itself when the two approval gates are
	 * merged, a child Plan issue for a legacy Request.
	 */
	planNumber: number;
	/** The repository slug, `owner/name`. */
	repo: string;
	/**
	 * Reviewer feedback from a `reject`/`revise` comment. When present the plan is re-run with the
	 * feedback instead of starting over.
	 */
	feedback?: string;
}

/**
 * Builds the prompt that asks for a plan.
 *
 * @param requestNumber - The parent Request's number.
 * @param title - The parent Request's title.
 * @param body - The parent Request's body.
 * @param feedback - Reviewer feedback the new plan must address, when there is any.
 * @returns The prompt.
 */
function planPrompt(requestNumber: number, title: string, body: string, feedback: string): string {
	const prompt =
		`Draft a detailed, step-by-step Implementation Plan for Request #${requestNumber}:\n` +
		`Title: ${title}\nDetails: ${body}\n\n` +
		"Include Scope, Architectural & Code Changes, and Verification Steps.\n" +
		"Cite repository files as plain `path/to/file` code spans, never as file:// URLs.";
	if (!feedback) return prompt;
	return (
		prompt +
		"\n\nThe previous plan was rejected with this reviewer feedback, " +
		`which must be addressed in the new plan:\n"${feedback}"`
	);
}

/**
 * Generates and posts an implementation plan on the plan issue.
 *
 * Replaces `handle_plan`. The plan comment carries {@link PLAN_MARKER} as well as its heading,
 * because both gates live on one issue and something has to say which gate an `approve` is
 * answering; the marker is the reliable signal and the heading is what predates it.
 *
 * @param context - The handler's GitHub port, agent, and reporting.
 * @param request - The Request to plan for, the issue to plan on, and any reviewer feedback.
 * @returns What planning did.
 * @throws {@link AgentRunFailure} when the agent fails, after the error comment is posted.
 */
export async function handlePlan(context: PipelineContext, request: PlanRequest): Promise<PlanOutcome> {
	const { repo, requestNumber, planNumber, feedback = "" } = request;
	const { io } = context;

	const issue = await io.issueView(repo, requestNumber, ["title", "body"]);
	const planBody = await context.runAgentPrompt({
		prompt: planPrompt(requestNumber, issue.title, issue.body, feedback),
		kind: "plan",
		timeout: PLAN_TIMEOUT,
		checkpoint: {
			issueNumber: planNumber,
			repo,
			isPr: false,
			completedSteps: [`Reviewed Parent Request #${requestNumber}`, `Created child Plan issue #${planNumber}`],
		},
	});

	if (isQuotaExhaustionNotice(planBody)) {
		return { kind: "quota-exhausted", notice: planBody };
	}

	if (planBody.startsWith(AGENT_ERROR_PREFIX)) {
		// The parent Request is named in the error comment, which the merged-gate flow posts on the
		// plan issue: with both gates on one issue there is no second place for the reader to look.
		const comment =
			`${AGENT_MARKER}\n### DarkFactory Agent Execution Error\n\n` +
			`- **Parent Request**: #${requestNumber}\n\n${planBody}\n`;
		await io.addComment(repo, planNumber, comment);
		context.fail(`Plan failed on issue #${planNumber}; Execution Error posted.`);
	}

	const comment =
		`${AGENT_MARKER}\n${PLAN_MARKER}\n` +
		"### Implementation Plan (Autogenerated by the DarkFactory Agent)\n\n" +
		`- **Parent Request**: #${requestNumber}\n\n` +
		`${rewriteFileLinks(planBody, repo, context.developmentBranch)}\n\n` +
		`---\n*${PLAN_FOOTER}.*`;
	await io.addComment(repo, planNumber, comment);
	context.say(`Plan posted on issue #${planNumber}`);
	return { kind: "posted", comment };
}

/**
 * Reports whether an implementation plan has already been posted on an issue.
 *
 * Replaces `has_plan`. One issue carries both approval gates, so which gate the next `approve` is
 * answering is read back from the issue rather than tracked in a label or a second issue.
 *
 * An issue that cannot be read counts as having no plan, which re-plans safely: planning twice
 * wastes a run, while approving a plan that was never posted stalls the pipeline on nothing.
 *
 * @param context - The handler's GitHub port and reporting.
 * @param issueNumber - The issue to inspect.
 * @param repo - The repository slug, `owner/name`.
 * @returns Whether a plan comment is present.
 */
export async function hasPlan(context: PipelineContext, issueNumber: number, repo: string): Promise<boolean> {
	const issue = await bestEffort(
		`read comments on #${issueNumber}`,
		() => context.io.issueView(repo, issueNumber, ["comments"]),
		context.warn,
	);
	if (issue === undefined) return false;
	return issue.comments.some(isPlanComment);
}
