import { describe, expect, test } from "bun:test";
import { AgentRunFailure } from "../../src/pipeline/handler-context.ts";
import { handlePlan, hasPlan } from "../../src/pipeline/plan.ts";
import { PLAN_MARKER } from "../../src/pipeline/plan-scope.ts";
import { AGENT_ERROR_PREFIX, QUOTA_EXHAUSTED_NOTICE } from "../../src/pipeline/signals.ts";
import { handlerContext, operations, postedComments, recordingIo } from "./handlers.ts";

const REPO = "marius-patrik/DarkFactory";
const REQUEST = {
	title: "Request: self-review loop stalls on a repeated digest",
	body: "The agent harness reports the same review digest twice.",
};
const PLAN = "## Scope\n- `packages/harness/src/pipeline/review-convergence.ts`\n\n## Verification\nRun the suite.";

describe("handlePlan: the ordinary path", () => {
	test("reads the parent Request, asks the agent, then posts on the plan issue", async () => {
		// The plan is read from the parent Request but posted on the plan issue, so the two numbers
		// are not interchangeable and the recording shows which is which.
		const recording = recordingIo({ 1148: REQUEST });
		const { context, reported } = handlerContext({ io: recording.io, answers: [PLAN] });

		const outcome = await handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		expect(operations(recording)).toEqual(["issueView", "addComment"]);
		expect(recording.calls[0]?.args).toEqual([REPO, 1148, ["title", "body"]]);
		expect(recording.calls[1]?.args[1]).toBe(1150);
		expect(reported).toEqual(["Plan posted on issue #1150"]);
		expect(outcome.kind).toBe("posted");
	});

	test("a plan is the longest prompt before implementation, so it carries the plan timeout", async () => {
		const recording = recordingIo({ 1148: REQUEST });
		const { context, agent } = handlerContext({ io: recording.io, answers: [PLAN] });

		await handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		expect(agent.requests[0]?.kind).toBe("plan");
		expect(agent.requests[0]?.timeout).toBe("15m0s");
	});

	test("the plan comment carries the marker, because one issue carries both approval gates", async () => {
		// Without the marker nothing says which gate an `approve` is answering, because both gates
		// live on the same issue.
		const recording = recordingIo({ 1148: REQUEST });
		const { context } = handlerContext({ io: recording.io, answers: [PLAN] });

		await handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		const comment = postedComments(recording)[0] ?? "";
		expect(comment).toContain(PLAN_MARKER);
		expect(comment).toContain("### Implementation Plan (Autogenerated by the DarkFactory Agent)");
		expect(comment).toContain("- **Parent Request**: #1148");
		expect(comment).toContain(
			"---\n*Reply with `/df approve` to start implementation or `/df reject <feedback>` to revise the plan.*",
		);
	});

	test("the checkpoint names the plan issue, not the Request it was read from", async () => {
		// A resume restarts from the checkpoint, so recording the wrong number resumes the wrong
		// issue - the plan issue is the one a run is working on.
		const recording = recordingIo({ 1148: REQUEST });
		const { context, agent } = handlerContext({ io: recording.io, answers: [PLAN] });

		await handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		expect(agent.requests[0]?.checkpoint).toEqual({
			issueNumber: 1150,
			repo: REPO,
			isPr: false,
			completedSteps: ["Reviewed Parent Request #1148", "Created child Plan issue #1150"],
		});
	});

	test("a merged-gate issue plans itself, so both numbers are the same", async () => {
		const recording = recordingIo({ 1148: REQUEST });
		const { context } = handlerContext({ io: recording.io, answers: [PLAN] });

		await handlePlan(context, { requestNumber: 1148, planNumber: 1148, repo: REPO });

		expect(recording.calls[0]?.args[1]).toBe(1148);
		expect(recording.calls[1]?.args[1]).toBe(1148);
	});
});

describe("handlePlan: re-running on reviewer feedback", () => {
	test("feedback reaches the prompt, and the plan is re-run rather than started over", async () => {
		const recording = recordingIo({ 1148: REQUEST });
		const { context, agent } = handlerContext({ io: recording.io, answers: [PLAN] });

		await handlePlan(context, {
			requestNumber: 1148,
			planNumber: 1150,
			repo: REPO,
			feedback: "Say which tests prove the digest is stale.",
		});

		expect(agent.requests).toHaveLength(1);
		expect(agent.requests[0]?.prompt).toContain(
			'The previous plan was rejected with this reviewer feedback, which must be addressed in the new plan:\n"Say which tests prove the digest is stale."',
		);
	});
});

describe("handlePlan: failure paths", () => {
	test("a quota notice posts nothing and is not a failure", async () => {
		const recording = recordingIo({ 1148: REQUEST });
		const { context, reported } = handlerContext({ io: recording.io, answers: [QUOTA_EXHAUSTED_NOTICE] });

		const outcome = await handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		expect(operations(recording)).toEqual(["issueView"]);
		expect(reported).toEqual([]);
		expect(outcome).toEqual({ kind: "quota-exhausted", notice: QUOTA_EXHAUSTED_NOTICE });
	});

	test("an agent failure posts the error comment naming the parent, and ends the run non-zero", async () => {
		const recording = recordingIo({ 1148: REQUEST });
		const { context } = handlerContext({ io: recording.io, answers: [`${AGENT_ERROR_PREFIX}: quota gone`] });

		const failing = handlePlan(context, { requestNumber: 1148, planNumber: 1150, repo: REPO });

		await expect(failing).rejects.toBeInstanceOf(AgentRunFailure);
		expect(postedComments(recording)).toEqual([
			`<!-- darkfactory-agent -->\n### DarkFactory Agent Execution Error\n\n- **Parent Request**: #1148\n\n${AGENT_ERROR_PREFIX}: quota gone\n`,
		]);
	});

	test("a Request that cannot be read throws, because there is nothing to plan", async () => {
		const recording = recordingIo({}, { issueView: new Error("Not Found") });
		const { context } = handlerContext({ io: recording.io, answers: [PLAN] });

		expect(handlePlan(context, { requestNumber: 999, planNumber: 999, repo: REPO })).rejects.toThrow("Not Found");
	});
});

describe("hasPlan: reading back which gate an approval answers", () => {
	test("a marker on a comment means a plan is already posted", async () => {
		const recording = recordingIo({ 1148: { comments: [`<!-- darkfactory-agent -->\n${PLAN_MARKER}\n## Scope`] } });
		const { context } = handlerContext({ io: recording.io });

		expect(await hasPlan(context, 1148, REPO)).toBe(true);
	});

	test("a heading with no marker still counts, because plans predate the marker", async () => {
		// Plans posted before the two gates were merged carry only the heading. Treating those as
		// unplanned planned the first issue through the merged flow a second time.
		const recording = recordingIo({ 1148: { comments: ["### Implementation Plan\n\n## Scope"] } });
		const { context } = handlerContext({ io: recording.io });

		expect(await hasPlan(context, 1148, REPO)).toBe(true);
	});

	test("an issue with only feedback on it has no plan", async () => {
		const recording = recordingIo({
			1148: { comments: ["this is not a plan", "### DarkFactory Agent Interpretation\n\nIt stalls."] },
		});
		const { context } = handlerContext({ io: recording.io });

		expect(await hasPlan(context, 1148, REPO)).toBe(false);
	});

	test("an unreadable issue counts as having no plan, which re-plans safely", async () => {
		// Planning twice wastes a run; approving a plan that was never posted stalls the pipeline on
		// nothing. The Python chose the wasteful failure.
		const recording = recordingIo({}, { issueView: new Error("Not Found") });
		const { context, reported } = handlerContext({ io: recording.io });

		expect(await hasPlan(context, 1148, REPO)).toBe(false);
		expect(reported[0]).toContain("Could not read comments on #1148: Not Found");
	});
});
