// 3.4 Implementation and automatic review.
//
// Two of the four corrections live here, and both are stated as properties of the
// described revision rather than as a list of fixes: the review loop is bounded at three
// iterations and can end without a verdict, and the deterministic check runs once and
// therefore reports rather than blocks.
#heading(level: 2)[Implementace a automatická revize]

Po schválení plánu runner vytvoří nebo načte pracovní větev odvozenou z výchozí větve. Implementační instrukce obsahuje schválený plán, omezení na jeho rozsah a pravidla pro testy a dokumentaci. Harness následně může procházet repozitář, upravovat soubory a používat nástroje nad `/workspace`; změny zůstávají izolované mimo výchozí větev.

Po implementaci runner spustí dostupné formátovací nástroje a deklarované testovací sady. Při neúspěchu předá výstup kontroly agentnímu kroku `fix`, který má opravit chybu bez opuštění schváleného rozsahu. Testovací sady se přitom spouštějí pouze jednou a po opravě už ne: kód se zformátuje, zakomituje a odešle dál, i kdyby opravená verze stále neprocházela. Opakovatelná kontrola tedy rozliší dobrý a špatný stav, ale není překážkou — změna s neprocházejícími testy se dostane do draft pull requestu stejně jako změna procházející. Následně runner vytvoří commit, odešle větev a otevře draft pull request, čímž se oddělí samotná změna od jejího posouzení: implementace může být dokončena, ale pull request ještě není připraven k merge @darkfactory-d576ec8f.

Na draft pull requestu začíná automatická review smyčka. Každá iterace načte aktuální větev a diff a předá jej modelové revizi; souběžně běží průběžná integrace, tedy formátovací nástroje a testovací sady, jejichž výsledek je návratový kód. Nalezený problém runner zveřejní a spustí nový běh s fází opravy, která změní větev a spustí další review. Smyčka je ohraničena nejvýše třemi iteracemi a oprava, která větev nezmění, ji ukončí dřív. Po vyčerpání tří iterací však smyčka skončí bez jakéhokoli verdiktu, žádný komentář o vyčerpání nezanechá a pull request zůstane ve stavu draft, takže nikdo zvenčí nepozná, zda review prošlo, nebo se jen zastavilo. Jediným stavem, který v této revizi znamená zablokování, je vyčerpaná kvóta — tehdy se zapíše kontrolní bod, stav na projektové tabuli a komentář s výzvou k obnovení @darkfactory-d576ec8f.

@fig-issue-template ukazuje požadavek podaný právě kvůli této meze: žádá, aby se běh po třech opakováních stejného nálezu #emph[zastavil a napsal to výslovně do issue]. Popsaná revize to neumí, ať žádá o třetí opakování; podmínka zastavení je přitom v dokumentaci, na níž se tato kapitola opírá, uvedena výslovně @openai-goals. Jde tedy o mezeru, kterou systém do této revize nemá a kterou práce zaznamenává, nikoli o vlastnost, kterou by měl.

Po čisté review ještě proběhne kontrola souladu výsledného diffu se schváleným plánem. Ani ta není porovnáním sad souborů: je to druhý dotaz modelu, tentokrát na shodu s textem plánu. Teprve když oba dotazy vyjdou bez nálezu, je draft pull request označen jako připravený k lidské revizi. Tento krok je důležitý, protože automatická revize může skončit bez nálezu, aniž by sama zaručila, že implementace odpovídá původnímu zadání. Jeho mez plyne z podstaty: posuzuje plán, jehož text napsal tentýž model, a sahat do stavu repozitáře umí jen na základě toho, co mu pipeline předala. Dodavatelé tento typ hodnotitele popisují stejně omezeně @claude-goal, a je proto zde s první branou rovnocenný, ne její náhradou.
