// 4.2 Discussion.
#heading(level: 2)[Diskuse] <diskuse>

Zjištění lze interpretovat jako konkrétní podobu Agentického inženýrství: praktická autonomie není vlastností samotného modelu, ale výsledkem návrhu prostředí, v němž model pracuje. GitHub poskytuje trvalý kontext a lidskou odpovědnost, Python určuje přechody mezi kroky, Docker omezuje běhové prostředí a harness propojuje model s nástroji a pozorováními. Tato dělba odpovědnosti je v souladu s principy efektivního a kontrolovaného systému popsanými v teoretické části @anthropic-harness-design @anthropic-managed-agents @darkfactory-d576ec8f.

Review smyčka ukazuje výhodu a zároveň omezení průběžné kontroly. Testy a formátovací nástroje poskytují zpětnou vazbu, kterou lze opakovat, ale ani druhá brána — kontrola souladu s plánem — deterministická není: jde o druhý dotaz modelu, a je tedy stejně pravděpodobnostní jako review, které jí předchází. Opakované iterace zvyšují počet příležitostí k nálezu, nikoli záruku konečné správnosti. Zablokování při opakování stejného nálezu je proto rozumnou ochranou před nekonečným během, nikoli důkazem vyřešení problému @darkfactory-d576ec8f.

Jednoduchost návrhu má také ekonomickou a epistemickou cenu. Nevyžaduje žádnou vlastní infrastrukturu a celý průběh je dohledatelný v issue, commitech, kontrolách a pull requestu. Na druhé straně pipeline závisí na dostupnosti GitHubu, kvalitě issue, schopnosti modelu pracovat s nástroji a pravidlech, která definují akceptační podmínky. Jednoduchá architektura tedy usnadňuje reprodukci postupu, ale nenahrazuje odpovědnost člověka za architekturu, bezpečnost a přijetí výsledku @darkfactory-d576ec8f.

Opakovatelná a pravděpodobnostní pozorování se proto doplňují, nenahrazují. Formátovací nástroje a testy poskytují pozorování, které se dá opakovat; review, kontrola souladu s plánem, plánování a opravy interpretují zadání a neočekávané nálezy. Z toho plyne, že obě brány před sloučením nejsou nezávislé: jsou to dva dotazy téhož druhu, a druhý z nich navíc vychází z plánu, jehož text sám napsal model. Tato kombinace odpovídá cíli Agentického inženýrství zvýšit užitečnost delegované práce při zachování explicitních bran, ale její skutečná kvalita zůstává závislá na datech, promptu, modelu a konkrétním repozitáři @darkfactory-d576ec8f.

#heading(level: 3)[Omezení výzkumu]

Praktická část má omezení, která je třeba pojmenovat, protože se dotýkají platnosti závěrů. Spočívají ve dvou vrstvách.

První je vlastnictví. Agentickou smyčku v popsané realizaci neautor navrhuje: sestavuje ji cizí harness, která spravuje kontext, volá nástroje a vyřizuje oprávnění. Co autor navrhuje, je vrstva nad ní, tedy stavový stroj, který rozhoduje, kdy se smyčka spustí, co smí agent změnit a kde práce skončí. Odpověď na výzkumnou otázku je tím užší, než kdyby smyčka byla implementována od začátku, a je takto i formulována.

Druhé je rozsah. Zkoumaný stav je záměrně jen počáteční: řadič volá cizí harnessy a všechny agentní kroky vede přes ně. Popisuje tedy míru autonomie dosažitelnou bez vlastního harnessu, nikoli míru dosažitelnou s ním, a tím záměrně neřeší otázku, kterou řeší práce následující. Tvrzení práce se proto vztahuje k této konfiguraci a je opřeno o konkrétní revizi @darkfactory-d576ec8f.

Z prvního omezení plyne i obrana závěrů. Harness je v popsané architektuře zaměnitelná závislost, stejně jako databáze nebo runner. Co práce především ukazuje, není volba konkrétního CLI, ale struktura procesu: že požadavek musí projít interpretací, plánem a dvěma lidskými branami dříve, než vznikne větev, a že změna se přebírá jako konkrétní revize na jednom pull requestu, dokud nesplní obě brány. Tato struktura je vůči tomu, kdo vykonává modelové kroky, invariantní. Právě to je obsahem Agentického inženýrství ve smyslu vymezeném v teoretické části, a právě to zůstává platné i tehdy, když se harness, jehož rozhraní je popsáno výše, přestane používat. Hypotéza je tím potvrzena v užší podobě, než byla formulována: autonomie je dosažitelná bez vlastního harnessu, ale její kvalita je omezena kvalitou cizí smyčky, kterou autor neovládá.
