// 4.2 Discussion.
#heading(level: 2)[Diskuse] <diskuse>

Zjištění lze interpretovat jako konkrétní podobu agentického inženýrství: praktická autonomie není vlastností samotného modelu, ale výsledkem návrhu prostředí, v němž model pracuje. GitHub poskytuje trvalý kontext a lidskou odpovědnost, Python určuje přechody mezi kroky, Docker omezuje běhové prostředí a harness propojuje model s nástroji a pozorováními @darkfactory-d576ec8f. Tato dělba odpovědnosti odpovídá tomu, jak obor takové systémy popisuje @anthropic-harness-design @anthropic-managed-agents.

Review smyčka ukazuje výhodu a zároveň omezení průběžné kontroly. Testy a formátovací nástroje poskytují zpětnou vazbu, kterou lze opakovat, ale ani druhá brána — kontrola souladu s plánem — deterministická není: jde o druhý dotaz modelu, a je tedy stejně pravděpodobnostní jako review, které jí předchází. Opakované iterace zvyšují počet příležitostí k nálezu, nikoli záruku konečné správnosti. Zastavení po vyčerpání iterací je ochranou před nekonečným během, ale bez zaznamenaného verdiktu není ani touto ochranou úplně: kdo se později ptá na stav, nemá v issue co číst @darkfactory-d576ec8f.

Záporné zjištění ukázalo i druhou věc. Opakovatelná kontrola v této revizi rozliší dobrý a špatný stav, ale není překážkou: testy běží jednou a po opravě už ne, takže změna, která neprošla, se do pull requestu dostane stejně jako změna, která prošla. Rozlišení mezi kontrolou, která brání, a kontrolou, která pouze hlásí, je tedy neúplné, a je to vlastnost konfigurace, nikoli principu. Dodavatelé, kteří takovou bránu prodávají, popisují její omezení shodně: hodnotitel nevolá nástroje a posuzuje jen to, co pracující model sám ukázal @claude-goal. Samoshodnocení agentů selhává určeným směrem @anthropic-harness-design. Rozdělení práce od hodnocení tedy shovívavost neodstraňuje samo o sobě; odstraňuje ji až to, že kontrolu, kterou by bylo možné zopakovat, zajišťuje návratový kód místo názoru.

Jednoduchost návrhu má také ekonomickou a epistemickou cenu. Nevyžaduje žádnou vlastní infrastrukturu a celý průběh je dohledatelný v issue, commitech, kontrolách a pull requestu. Na druhé straně pipeline závisí na dostupnosti GitHubu, kvalitě issue, schopnosti modelu pracovat s nástroji a pravidlech, která definují akceptační podmínky. Jednoduchá architektura tedy usnadňuje reprodukci postupu, ale nenahrazuje odpovědnost člověka za architekturu, bezpečnost a přijetí výsledku @darkfactory-d576ec8f.

Opakovatelná a pravděpodobnostní pozorování se proto doplňují, ale nenahrazují. Formátovací nástroje a testy poskytují pozorování, které se dá opakovat; review, kontrola souladu s plánem, plánování a opravy interpretují zadání a neočekávané nálezy. Z toho plyne, že obě brány před sloučením nejsou nezávislé: jsou to dva dotazy téhož druhu, a druhý z nich navíc vychází z plánu, jehož text sám napsal model. Tato kombinace odpovídá cíli agentického inženýrství zvýšit užitečnost delegované práce při zachování explicitních bran, ale její skutečná kvalita zůstává závislá na datech, promptu, modelu a konkrétním repozitáři @darkfactory-d576ec8f.

Praktická část má omezení, která je třeba pojmenovat, protože se dotýkají platnosti závěrů. Spočívají ve třech vrstvách.

První je vlastnictví. Agentní smyčku v popsané realizaci autor nenavrhuje: sestavuje ji cizí harness, která spravuje kontext, volá nástroje a vyřizuje oprávnění. Co autor navrhuje, je vrstva nad ní, tedy runner, který rozhoduje, kdy se smyčka spustí, co smí agent změnit a kde práce skončí. Odpověď na výzkumnou otázku je tím užší, než kdyby smyčka byla implementována od začátku, a je takto i formulována.

Druhé je rozsah. Zkoumaný stav je záměrně jen počáteční: runner volá cizí harnessy a všechny agentní kroky vede přes ně. Jde tedy o míru autonomie dosažitelnou touto konkrétní konfigurací, nikoli o míru dosažitelnou s vlastní smyčkou, a tím záměrně neřeší otázku, kterou řeší práce následující. Tvrzení práce se proto vztahuje k této konfiguraci a je opřeno o konkrétní revizi @darkfactory-d576ec8f.

Třetí je složení vrstev. Popsaný systém má nad sebou dvě vrstvy harnessu: vnější runner s branami a uloženým stavem, vnitřní produkční CLI, které modelové kroky vykonává. Během jednoho běhu se tedy model setkává se dvěma sadami pravidel současně, a to, kterému pravidlu se podřizuje a co vnější vrstva stojí, zůstává nezodpovězené. Část odpovědi je přesto veřejně dostupná: dokumentace vrstvení běhů rozlišuje předání práce, při němž zůstává jediný cyklus, od volání agenta jako nástroje, při němž vzniká vnořený běh s vlastním cyklem, limitem iterací a žádostmi o schválení. Neurčuje však výši nákladu — „the nested turns do not increment the outer run’s turn counter“ @openai-agents-sandbox — takže účetnictví vnější vrstvy práci vnořeného běhu nevidí. Zda je takový náklad v popsaném systému významný, zjištěno nebylo.

Z prvního omezení plyne i obrana závěrů. Harness je v popsané architektuře zaměnitelnou závislostí, stejně jako databáze nebo runner. Co práce především ukazuje, není volba konkrétního CLI, ale struktura procesu: že požadavek musí projít interpretací, plánem a dvěma lidskými branami dříve, než vznikne větev, a že změna se přebírá jako konkrétní revize na jednom pull requestu, dokud nesplní obě brány. Tato struktura je vůči tomu, kdo vykonává modelové kroky, invariantní. Právě to je obsahem agentického inženýrství ve smyslu vymezeném v teoretické části: jde o vlastnost této práce, neboť popsaná struktura je záměrem autora a nezávisí na tom, kdo vykonává modelové kroky. To však není obecná zákonitost, a závěr práce proto přenositelnost struktury na libovolný nástroj neprokazuje; naopak, tam, kde se konvence přenášejí z jednoho typu běhu do druhého, je výsledek opačný @thangarajah2026dcas. Hypotéza se potvrzuje: strukturu, kterou práci řídí, autor navrhuje sám, zatímco úsudek o tom, co je v jednotlivém kroku správné, přebírá od smyčky, kterou nevlastní.
